Semantics checks
GneyHabub/iCompiler pull request #30
Opened 2020-10-06 10:56 UTC by rusya-ink

- parameter
- neq operator
- neg operator
- add operator
- variable declaration
- integer literal
- greater operator

2020-10-06 19:41 UTC, GneyHabub requested changes

2020-10-06 19:41 UTC, GneyHabub commented on ast-nodes/variable-declaration.dart
> +    ensureType(this.value, this.type);
`ensureType` produces no meaningful side effect, it returns a value. Also, `this.value` and `this.type` might both be `null` and `ensureType` will crash if you pass null as an argument.

2020-10-06 19:41 UTC, GneyHabub commented on ast-nodes/expressions/operators/greater-operator.dart
> +    }
You have the same mistake as I had. We can compare bools, arrays and records only for equality, we cannot say if one is greater then another.

2020-10-06 19:41 UTC, GneyHabub commented on ast-nodes/expressions/operators/neg-operator.dart
> +    ensureType(this.operand, this.resultType);
You are the one that has to set the resulting type, you cannot use it. And the same mistake with `ensureType` as in one of the previous commits.

2020-10-07 12:25 UTC, illright requested changes

2020-10-07 12:25 UTC, illright commented on ast-nodes/expressions/operators/neg-operator.dart
> +    if (operand is IntegerType) {
You need to check `operand.resultType`, not just `operand`

2020-10-07 12:25 UTC, illright commented on ast-nodes/variable-declaration.dart
>      this.value.checkSemantics();
Use the optional chaining here (`?.`), both value and the type may be `null`.

2020-10-07 12:25 UTC, illright commented on ast-nodes/variable-declaration.dart
> +    if (this.type != null && this.value != null) {
Okay, I really don't understand what is going on in this piece of code. Let me tell you how I see this semantic check:
* if type is not null, check its semantics
* if value is not null, check its semantics
* if type is null, assign `this.type = this.value.returnType`
* if type is not null, ensure the value is convertible to the type

I don't know what are all those huge if statements about

2020-10-07 13:35 UTC, GneyHabub approved these changes

2020-10-08 09:30 UTC, illright approved these changes

2020-10-08 11:03 UTC, merged